[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# For monorepo deployment, you can specify which package to deploy
# by setting the working directory in Railway's service settings 