import { Stablecoin } from '@/types/stablecoin';

export const mockStablecoins: Stablecoin[] = [
  {
    id: 1,
    slug: 'usdc',
    name: 'USD Coin',
    token: 'USDC',
    peggedAsset: 'USD',
    issuer: 'Circle',
    tokenProgram: 'SPL Token',
    tokenAddress: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
    mintAuthority: 'Circle/Coinbase',
    // bridgingMechanisms: ['Wormhole', 'Allbridge'],
    // networksLiveOn: ['Ethereum', 'Solana', 'Avalanche', 'Polygon'],
    // redemptionMechanisms: ['Direct redemption through Circle', 'Exchange'],
    solscanLink: 'https://solscan.io/token/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
    artemisLink: 'https://artemis.xyz/token/usdc',
    assetReservesLink: 'https://www.circle.com/en/transparency',
    transactionVolume30d: '75000000000',
    transactionCountDaily: '1250000',
    totalSupply: '45000000000',
    dailyActiveUsers: '1250000',
    price: 1.00,
    executiveSummary:
      "USDC is a fully-backed stablecoin issued by Circle, with transparent reserves held in cash and short-term US Treasury bonds. It's the most widely used stablecoin on Solana with deep liquidity across DEXs and CEXs.",
    logoUrl: 'https://i.postimg.cc/y6mGy9m7/image.png',
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 2,
    slug: 'usdt',
    name: 'Tether',
    token: 'USDT',
    peggedAsset: 'USD',
    issuer: 'Tether Limited',
    tokenProgram: 'SPL Token',
    tokenAddress: 'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB',
    mintAuthority: 'Tether Limited',
    // bridgingMechanisms: ['Wormhole', 'Allbridge'],
    // networksLiveOn: ['Ethereum', 'Solana', 'Tron', 'BSC'],
    // redemptionMechanisms: ['Direct redemption through Tether', 'Exchange'],
    solscanLink: 'https://solscan.io/token/Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB',
    artemisLink: 'https://artemis.xyz/token/usdt',
    assetReservesLink: 'https://tether.to/en/transparency',
    transactionVolume30d: '63000000000',
    transactionCountDaily: '950000',
    totalSupply: '85000000000',
    dailyActiveUsers: '950000',
    price: 1.00,
    executiveSummary:
      'USDT is the largest stablecoin by market cap, issued by Tether Limited. While historically facing questions about its reserves, it maintains its peg and provides high liquidity across Solana DeFi.',
    logoUrl: 'https://cryptologos.cc/logos/tether-usdt-logo.png',
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 3,
    slug: 'pyusd',
    name: 'PayPal USD',
    token: 'PYUSD',
    peggedAsset: 'USD',
    issuer: 'PayPal',
    tokenProgram: 'Token 2022',
    tokenAddress: 'HYdzX8K9JKCYyRXq4jBwXkEAQnrfLZCjQQNhgHNdH3P9',
    mintAuthority: 'PayPal',
    // bridgingMechanisms: ['Wormhole', 'Portal Bridge'],
    // networksLiveOn: ['Ethereum', 'Solana'],
    // redemptionMechanisms: ['Direct redemption through PayPal', 'Exchange'],
    solscanLink: 'https://solscan.io/token/HYdzX8K9JKCYyRXq4jBwXkEAQnrfLZCjQQNhgHNdH3P9',
    artemisLink: 'https://artemis.xyz/token/pyusd',
    assetReservesLink: 'https://www.paypal.com/pyusd/transparency',
    transactionVolume30d: '1500000000',
    transactionCountDaily: '125000',
    totalSupply: '750000000',
    dailyActiveUsers: '125000',
    price: 1.00,
    executiveSummary:
      "PYUSD is PayPal's stablecoin, fully backed by USD deposits, US Treasuries and cash equivalents. Its integration with PayPal's payment infrastructure provides a bridge between traditional finance and crypto.",
    logoUrl: 'https://cryptologos.cc/logos/paypal-pyusd-logo.png',
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 4,
    slug: 'uxd',
    name: 'UXD Stablecoin',
    token: 'UXD',
    peggedAsset: 'USD',
    issuer: 'UXD Protocol',
    tokenProgram: 'SPL Token',
    tokenAddress: '7kbnvuGBxxj8AG9qp8Scn56muWGaRaFqxg1FsRp3PaFT',
    mintAuthority: 'UXD Protocol',
    // bridgingMechanisms: ['Native to Solana'],
    // networksLiveOn: ['Solana'],
    // redemptionMechanisms: ['UXD Protocol', 'DEX'],
    solscanLink: 'https://solscan.io/token/7kbnvuGBxxj8AG9qp8Scn56muWGaRaFqxg1FsRp3PaFT',
    artemisLink: 'https://artemis.xyz/token/uxd',
    assetReservesLink: 'https://uxd.fi/transparency',
    transactionVolume30d: '255000000',
    transactionCountDaily: '32000',
    totalSupply: '85000000',
    dailyActiveUsers: '32000',
    price: 1.00,
    executiveSummary:
      'UXD is an algorithmic stablecoin that maintains its peg through delta-neutral positions using derivatives. This design allows for a fully decentralized stablecoin without governance control.',
    logoUrl: 'https://assets.coingecko.com/coins/images/25444/small/uxd-icon-dark.png',
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
];

export const solanaStablecoinStats = {
  totalMarketCap: 46500000000, // Total market cap of all stablecoins on Solana
  totalUniqueUsers: 1750000, // Total unique addresses using stablecoins
  totalTransactionVolume: {
    daily: 2750000000,
    monthly: 82500000000,
    yearly: 990000000000,
  },
  percentageOfSolanaVolume: 42, // Percentage of total Solana volume
  stablecoinCount: 12, // Total number of tracked stablecoins
  dominantStablecoin: 'USDC', // Most used stablecoin
  dominantStablecoinShare: 78, // Market share percentage of dominant stablecoin
  yearOverYearGrowth: 35, // YoY growth percentage
};
